Update install-shellcheck
Added root/sudo check.

diff --git a/install-shellcheck b/install-shellcheck
--- a/install-shellcheck
+++ b/install-shellcheck
@@ -33,6 +33,12 @@
 
 # This was created and tested on Debian 8.1, RHEL/CentOS testing is TBD
 
+# Check that we're root
+if [[ ! ${EUID} = 0 ]]; then
+  printf "%s\n" "ERROR: This script must be run as root or with appropriate sudo rights."
+  exit 1
+fi
+
 # Variables
 WrkPrcs=$(lscpu | grep "^CPU(s)" | awk '{print $2}')
 HostName=$(hostname -f)
