Update rand
Updated method_RANDOM.  Fn_lcgrng is now merged into it, with failover if $RANDOM is not found.  This means the old method_manual and its related functions can be outright removed.  Hooray!

diff --git a/rand b/rand
--- a/rand
+++ b/rand
@@ -20,8 +20,8 @@
 # Set the default variable states
 nMin=1
 #nMax=32767
-nMax=4294967295           #2^32-1
-#nMax=72057594037927935    #2^56-1
+nMax=4294967295             #2^32-1
+#nMax=72057594037927935     #2^56-1
 #nMax=9223372036854775807   #2^63-1
 debug=false
 nCount=1
@@ -73,6 +73,13 @@ if [ "${nMin}" -ge "${nMax}" ]; then
   exit 1
 fi
 
+# Easter Egg
+if [ "${nMax}" -gt 9223372036854775807 ]; then
+  printf "%s\n" "[INFO] rand: Come on now, stop being silly." \
+    "My upper boundary is *sometimes* 9223372036854775807."
+  exit 1
+fi
+
 # Put these vars into the environment so we can import them to perl etc
 export nMin nMax nCount
 
@@ -87,13 +94,6 @@ Fn_bitlen() {
     logn=$(( logn * 2 ))
     nBitlen=$(( nBitlen + 1 ))
   done
-}
-
-# Function to quickly rotate ASCII characters by 90 places
-# emulates Fn_xor in a lazy way but is infinitely faster
-Fn_chrotate() {
-  # shellcheck disable=SC2020
-  tr ' !"#$%&()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~' 'z{|}~ !"#$%&()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxy'
 }
 
 # This function ensures equal distribution for methods that don't support it
@@ -137,34 +137,6 @@ Fn_fill() {
   fi
 }
 
-# Linear congruential generator, range 0 - 32767
-# See: https://rosettacode.org/wiki/Linear_congruential_generator
-# Usage: Fn_lcgrng (optional: number count, default:1) (optional: seed, default: epoch in seconds)
-Fn_lcgrng() {
-  rnCount="${1:-1}"
-  rnSeed="${2:-$(date +%s)}"
-
-  # Here's an unnecessary nod to FreeBSD's rand.c
-  if [ "${rnSeed}" = 0 ]; then
-    rnSeed=123459876
-  fi
-
-  while [ "${rnCount}" -gt 0 ]; do
-    # BSD style modulus'ed against 2^31
-    rnSeed=$(( (1103515245 * rnSeed + 12345) % 2147483648 ))
-    
-    # Microsoft style
-    #rnSeed=$(( (214013 * rnSeed + 2531011) % 2147483648 ))
-
-    # print the generated number as an unsigned int (i.e. positive decimal)
-    # Divided by 2^16
-    printf "%u\n" "$(( rnSeed / 65536 ))"
-
-    # Decrement the counter
-    rnCount=$(( rnCount - 1 ))
-  done
-}
-
 # This function allows us to print out unsorted, unique integers
 Fn_unique() {
   # If 'awk' is available, we use it
@@ -177,19 +149,6 @@ Fn_unique() {
   else
     nl | sort -k 2 -u | sort | cut -f2
   fi
-}
-
-# xor function derived from http://zurlinux.com/?p=712
-Fn_xor() {
-  while read -r line; do
-    # Start by removing whitespace to reduce character bias
-    # pipe to 'od' which converts each character to one octal per line
-    for i in $(printf "%s" "${line}" | tr -d " " | od -A n -t o1 -w1 -v); do
-      # for each octal, run an xor and then print it
-      # shellcheck disable=SC2059
-      printf \\"$(printf '%03o' "$(( i ^ 90 ))" )"
-    done
-  done
 }
 
 # Setup the zeropad function
@@ -219,111 +178,6 @@ method_jot() {
   jot -w %i -r "${nCount}" "${nMin}" "${nMax}"
 }
 
-# Function to generate numbers using manual entropy generation
-method_manual() {
-  # Check we have the required binaries
-  ErrCount=0
-  for Prog in od tr tail head; do
-    if ! command -v "${Prog}" >/dev/null 2>&1; then
-      printf "%s\n" "[ERROR] rand: '${Prog}' is required but was not found."
-      ErrCount=$(( ErrCount + 1 ))
-    fi
-  done
-
-  # If any packages are missing, then ErrCount's going
-  # to be greater than 0, in which case, exit.
-  if [ "${ErrCount}" -gt 0 ]; then
-    exit 1
-  fi
-
-  # Let's try and find a hashing method, we use this sparingly for now
-  for cryptopt in sha256sum sha1sum shasum md5sum digest csum cksum; do
-    if command -v "${cryptopt}" > /dev/null 2>&1; then
-      crypt="${cryptopt}"
-      if [ "${crypt}" = digest ]; then
-        crypt="digest -v -a md5"
-      fi
-      break
-    else
-      printf "%s\n" "[ERROR] rand: 'manual entropy' method was selected, but no hash method is available."
-      exit 1
-    fi
-  done
-
-  # We need some "entropy", so let's first check for an existing entropy file from
-  # a previous invocation.  If found, we want to rotate its characters
-  if [ -f /tmp/entropy ]; then
-    Fn_chrotate < /tmp/entropy > /tmp/entropy2
-    mv /tmp/entropy2 /tmp/entropy
-
-  # Otherwise, let's generate some "entropy" by simply running through this list of commands
-  # And trying to remove as much whitespace as possible, then do a fast 'xor'
-  # Some of these may fail, so we redirect stderr into the stream anyway.  Throw it all at the wall, see what sticks.
-  else
-    {
-      vmstat -s
-      vmstat -c
-      pfstat
-      vmstat -i
-      netstat -s
-      nfsstat
-      netstat -m
-      netstat -in
-      mpstat
-      w
-      df
-      portstat
-      iostat
-      uptime
-      vmstat -f
-      vmstat
-      netstat -n
-      lsof
-      ps aux
-      ipcs -a
-      pstat -afipSsT
-      pstat -p
-      pstat -S
-      pstat -v
-      pstat -x
-      pstat -t
-      last -n 50
-      arp -a
-      ripquery -nw 1 127.0.0.1
-      lpstat -t
-      tcpdump -c 5 -efvvx
-    } 2>&1 | tr -d " " | tr -d "\n" | Fn_chrotate > /tmp/entropy
-  fi
-
-  while [ "${nCount}" -gt 0 ]; do
-
-    # Get a string of 4 bytes from /tmp/entropy using od
-    # format it as an unsigned integer between 0 and 2^32-1
-    nRand=$(od -N 4 -A n -t uL /tmp/entropy | tr -d " ")
-
-    # Pass nRand through a standard modulo
-    printf "%s\n" "$(( nRand % (nMax + 1 - nMin) + nMin ))"
-
-    # Decrement the counter
-    nCount=$(( nCount - 1 ))
-
-    # Now we have to churn the entropy file.  We remove the leading 32 Bytes 
-    # of the entropy file, and temporarily store the result
-    tail -c +33 /tmp/entropy | tr -d "\n" > /tmp/entropy2
-
-    {
-      # Seed some more data into the temporary entropy file, here we hash the PID
-      printf "%s" "$$" | Fn_xor | tr -d " " | tr -d "\n" | "${crypt}"
-      # Rotate the entropy, get the first 64 chars, xor it to the bottom of the temp file
-      printf "%s" "$(fold -b -w 64 /tmp/entropy | head -n 1 | Fn_xor)"
-      date '+%H%M%S' | Fn_xor | tr -d " " | tr -d "\n"
-    } >> /tmp/entropy2
-
-    # Move the temporary file into place
-    mv /tmp/entropy2 /tmp/entropy
-  done 
-}
-
 # Function to generate numbers using 'nawk'
 method_nawk() {
   nawk -v min="${nMin}" -v max="${nMax}" -v nNum="${nCount}" -v seed="$(date +%Y%M%d%H%M%S)" 'BEGIN {srand(seed); i = 0; while (i < nNum) { print int(min+rand()*(max-min)); ++i} }'
@@ -340,27 +194,47 @@ method_python() {
 }
 
 # Function to generate numbers using shell 'RANDOM' special variable
+# If the special variable isn't available, we fall back to
+# a BSD-style Linear congruential generator (LCG)
+# See: https://rosettacode.org/wiki/Linear_congruential_generator
 method_RANDOM() {
   # We need to know the number of bits required to represent nMax (i.e. bitlength)
   Fn_bitlen
 
+  # We set the initial seed just in case we're using the LCG
+  rnSeed=$(date +%s)
+
   # Start a loop based on nCount.  I thought of other ways, but this works easier
   # and can be made more portable if testing proves the need to do so
   while [ "${nCount}" -gt 0 ]; do
+    # Start generating seeds for the LCG
+    rnSeed=$(( (1103515245 * rnSeed + 12345) % 2147483648 ))
+    # If the RANDOM variable is blank, we failover to the LCG
+    # We print as an unsigned integer to ensure that it's a positive number
+    RANDOM="${RANDOM:-$(printf "%u\n" "$(( rnSeed / 65536 ))")}"
+    # Set our initial bitlength
     rndBitlen=15
-    rnd=$RANDOM # Capture one output sample of RANDOM
+    rnd="${RANDOM}" # Capture one output sample of RANDOM
+
     while [ "${rndBitlen}" -lt "${nBitlen}" ]; do
       # Bitshift RANDOM to the left to stack it i.e. 15 int -> 30 int -> 45 int etc
       rnd=$(( rnd<<15|RANDOM ))
       # Keep stacking until the while loop exits
       rndBitlen=$(( rndBitlen + 15 ))
+      rnSeed=$(( (1103515245 * rnSeed + 12345) % 2147483648 ))
+
+      # If two invocations of RANDOM are the same, then we're working with a
+      # shell that does not support $RANDOM.  So we use the LCG and rotate RANDOM
+      if [ "${RANDOM}" = "${RANDOM}" ]; then
+        RANDOM=$(printf "%u\n" "$(( rnSeed / 65536 ))")}
+      fi
     done
     # Now bitshift it right
     nRandShift=$(( rnd>>(rndBitlen-nBitlen) ))
 
     # Next we test if the number we've generated fits into our range.  If so,
     # then we can use it and iterate the while loop
-    # May need to add a check to 
+    # May need to add a check to
     if [ $((nRandShift + nMin)) -le "${nMax}" ]; then
       printf "%u\n" "$(( nRandShift + nMin ))"
       nCount=$(( nCount - 1 ))
@@ -550,23 +424,6 @@ elif [ -c /dev/urandom ]; then
   else
     Fn_fill method_urandom
   fi  
-
-# If there's no shuf, jot, perl, python, gawk, nawk, $RANDOM or /dev/urandom, then what savage OS are we on?
-# Let's try to make something up.  Let's be honest, though, by this point it's an academic exercise.
-#
-# Originally this was based off PID + date, but was rewritten to generate and churn a sufficient
-# amount of entropy.  Applying /dev/urandom processing gave a very skewed distribution
-# and so I decided to limit the number of bytes read and simply use a modulo formula
-# The point being that if we ever got to this point, it's enough to generate something.
-elif command -v date > /dev/null 2>&1; then
-  if [ "${debug}" = true ]; then
-    printf "%s\n" "[DEBUG] rand: Method used is 'manual entropy'"
-  fi
-  if [ "${repeat}" = true ]; then
-    method_manual
-  else
-    Fn_fill method_manual
-  fi
 
 # Ultimate failure
 else
